import = ["~/.config/alacritty/MonaLisa.toml"]

[window]

opacity = 0.7

dynamic_padding = true
decorations= "None"
startup_mode = "Windowed"

[scrolling]
multiplier = 6

[shell]
program = "/bin/bash"

[font]
normal = {family = "Fira Code", style = "Retina"}
glyph_offset = {x=-1, y =0}

[colors.primary]

[cursor]
style={shape = "Beam",blinking = "Always"}
unfocused_hollow = false

[mouse]
hide_when_typing = true
